DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS INTEREST;

CREATE TABLE IF NOT EXISTS INTEREST (
  INTEREST_ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(256),
  VERSION INT,
  IS_DELETED INT,
  CREATED_BY VARCHAR(128),
  CREATED_AT DATETIME,
  UPDATED_BY VARCHAR(128),
  UPDATED_AT TIMESTAMP,
  PRIMARY KEY (INTEREST_ID)
);

CREATE TABLE IF NOT EXISTS ITEM (
  ITEM_ID INT NOT NULL AUTO_INCREMENT,
  ARTICLE VARCHAR(8192),
  LINK VARCHAR(1024),
  FILE_PATH VARCHAR(1024),
  INTEREST_ID INT,
  VERSION INT,
  IS_DELETED INT,
  CREATED_BY VARCHAR(128),
  CREATED_AT DATETIME,
  UPDATED_BY VARCHAR(128),
  UPDATED_AT TIMESTAMP,
  PRIMARY KEY (ITEM_ID)
);
